services:
  openjdk17:
    image: dev-env-openjdk17:latest
    build:
      context: .
      dockerfile: Containerfile
    volumes:
      - ./workspace:/workspace:Z
    tty: true
    stdin_open: true
