FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    unzip \
    libaio1 \
    curl \
    openssh-client \
 && rm -rf /var/lib/apt/lists/*

ENV ORACLE_BASE=/opt/oracle
ENV LD_LIBRARY_PATH=$ORACLE_BASE/instantclient
ENV PATH=$PATH:$ORACLE_BASE/instantclient

WORKDIR /opt/oracle

COPY oracle-client/*.zip /opt/oracle/

RUN unzip instantclient-basiclite*zip && \
    unzip instantclient-sqlplus*zip && \
    ln -s instantclient_* instantclient && \
    rm *.zip

RUN pip install --no-cache-dir \
    python-oracledb \
    cx_Oracle

WORKDIR /workspace
CMD ["bash"]
